### ISSUE TITLE
Image TokenGrabber

### ISSUE THREAD

**Issue by deadunny** [AstraaDev/Daiho-Tool#1]
when i type the imggrab cmd it says `Non-operational...` ://

**Comment by AstraaDev** [comment]
Yeah because the option is not yet operational...

**Comment by deadunny** [comment]
oh.... do u have a date for it to be operational or is it still just a thought?

**Comment by AstraaDev** [comment]
I work on but it's soooo hard.

**Comment by deadunny** [comment]
i see i see, gonna be watching but ya gl w it :))
